

# Function to get the mapped value
def get_mapping(input_list_string):
    # Mapping data
    metabolist_list = {
    "6-ACETYLMORPHINE": "6-acetylmorphine",
    "METHAMPHETAMINE": "methamphetamine",
    "AMPHETAMINE": "amphetamine",
    "AMOBARBITAL": "amobarbital",
    "BUTALBITAL": "butalbital",
    "PHENOBARBITAL": "phenobarbital",
    "SECOBARBITAL": "secobarbital",
    "BUTABARBITAL": "butabarbital",
    "PENTOBARBITAL": "pentobarbital",
    "BENZOYLECGONINE-COCAINEMETABOLITE": "benzoylecgonine-cocaine",
    "OXAZEPAM": "oxazepam",
    "NORDIAZEPAM": "nordiazepam",
    "TEMAZEPAM": "temazepam",
    "ALPHA-HYDROXYALPRAZOLAM": "alpha-hydroxyalprazolam",
    "LORAZEPAM": "lorazepam",
    "7-AMINOCLONAZEPAM": "7-aminoclonazepam",
    "BUPRENORPHINE": "buprenorphine",
    "NORBUPRENORPHINE": "norbuprenorphine",
    "D-METHAMPHETAMINE": "d-methamphetamine",
    "L-METHAMPHETAMINE": "l-methamphetamine",
    "ETHANOL": "ethanol",
    "FENTANYL": "fentanyl",
    "NORFENTANYL": "norfentanyl",
    "MDA-METHYLENEDIOXYAMPHETAMINE": "mda-methylenedioxyamphetamine",
    "MDEA-METHYLENEDIOXYETHYLAMPHETAMINE": "mdea-methylenedioxyethylamphetamine",
    "MDMA-METHYLENEDIOXYMETHAMPHETAMINE": "mdma-methylenedioxymethamphetamine",
    "NORMEPERIDINE": "normeperidine",
    "MEPERIDINE": "meperidine",
    "METHAQUALONE": "methaqualone",
    "METHADONE METABOLITE- EDDP": "methadone-metabolite-eddp",
    "METHADONE": "methadone",
    "METHADONE METABOLITE": "methadone",
    "EXTENDED OPIATES (4)": "extended-opiates",
    "HYDROCODONE": "hydrocodone",
    "MORPHINE": "morphine",
    "CODEINE": "codeine",
    "Codeine / Morphine": 'codeine/morphine',
    "HYDROMORPHONE": "hydromorphone",
    "OXYMORPHONE": "oxymorphone",
    "OXYCODONE": "oxycodone",
    "PHENCYCLIDINE": "phencyclidine",
    "PROPOXYPHENE": "propoxyphene",
    "NORPROPOXYPHENE": "norpropoxyphene",
    "MARIJUANA METABOLITE": "marijuana",
    "NALBUPHINE": "nalbuphine",
    "PENTAZOCINE": "pentazocine",
    "O-DESMETHYLTRAMADOL": "o-desmethyltramadol",
    "TRAMADOL (ULTRAM)": "tramadol",
    "N-DESMETHYLTRAMADOL": "n-desmethyltramadol",
    "TRICYCLIC ANTIDEPRESSANTS": "tricyclic-antidepressants",
    "AMITRIPTYLINE": "amitriptyline",
    "DOXEPIN": "doxepin",
    "IMIPRAMINE": "imipramine",
    "DESIPRAMINE": "desipramine",
    "NORTRIPTYLINE": "nortriptyline",
    "TRIMIPRAMINE": "trimipramine",
    "EXTENDED BENZODIAZEPINES": "extended-benzodiazepines",
    "7-AMINO FLUNITRAZEPAM(FLUNITRAZEPAM METABOLITE)": "7-amino-flunitrazepam",
    "2-HYDROXY ETHYLFLURAZEPAM(FLURAZEPAM METABOLITE)": "2-hydroxy ethylflurazepam",
    "ALPHA-HYDROXYMIDAZOLAM": "alpha-hydroxymidazolam",
    "ALPHA-HYDROXYTRIAZOLAM": "alpha-hydroxytriazolam",
    "CODEINE / MORPHINE": "codeine-morphine",
    "COTININE": "cotinine",
    "ZOLPIDEM - AMBIEN": "zolpidem-ambien",
    "ZOLPIDEM CARBOXYLIC ACID": "zolpidem-carboxylic-acid",
    "BUTORPHANOL": "butorphanol",
    "MEPROBAMATE": "meprobamate",
    "CARISOPRODOLMETABOLITE": "carisoprodol",
    "CARISOPRODOL": "carisoprodol",
    "KETAMINE": "ketamine",
    "NORKETAMINE": "norketamine",
    "NALTREXONE": "naltrexone",
    "STIMULANTS": "stimulants",
    "PHENTERMINE": "phentermine",
    "PHENMETRAZINE": "phenmetrazine",
    "DIETHYLPROPION": "diethylpropion",
    "PHENDIMETRAZINE": "phendimetrazine",
    "HYDROCODONE / HYDROMORPHONE": "hydrocodone-hydromorphone",
    "SYNTHETIC CANNABINOIDS": "synthetic-cannabinoids",
    "RCS-4 PENTANOIC ACID": "rcs-4-pentanoic-acid",
    "JWH-018 PENTANOIC ACID": "jwh-018-pentanoic-acid",
    "JWH-081 5-HYDROXYPENTYL": "jwh-081-5-hydroxy-pentyl",
    "JWH-250 PENTANOIC ACID": "jwh-250-pentanoic-acid",
    "JWH-250 5-HYDROXYINDOLE": "jwh-250-5-hydroxy indole",
    "RCS-4 5-HYDROXYPENTYL": "rcs-4-5-hydroxy-pentyl",
    "JWH-018 HYDROXYPENTYL": "jwh-018-hydroxy-pentyl",
    "JWH-200 4-HYDROXYINDOLE": "jwh-200-4-hydroxy indole",
    "JWH-200 6-HYDROXYINDOLE": "jwh-200-6-hydroxy indole",
    "JWH-073 3-HYDROXYBUTYL": "jwh-073-3-hydroxy butyl",
    "JWH-073 4-HYDROXYBUTYL": "jwh-073-4-hydroxy butyl",
    "JWH-073 BUTANOIC ACID": "jwh-073-butanoic-acid",
    "JWH-250 5-HYDROXYPENTYL": "jwh-250-5-hydroxy-pentyl",
    "AM-2201 4-HYDROXYPENTYL": "am-2201-4-hydroxy-pentyl",
    "JWH-200 5-HYDROXY INDOLE": "jwh-200-5-hydroxy indole",
    "6-ACETYLMORPHINE ORAL FLUID": "6-acetylmorphine-oral-fluid",
    "MDA ORAL FLUID": "mda-oral-fluid",
    "AMPHETAMINE ORAL FLUID": "amphetamine-oral-fluid",
    "COCAINE ORAL FLUID": "cocaine-oral-fluid",
    "BENZOYLECGONINE ORAL FLUID": "benzoylecgonine-oral-fluid",
    "D-METHAMPHETAMINE ORAL FLUID": "d-methamphetamine-oral-fluid",
    "L-METHAMPHETAMINE ORAL FLUID": "l-methamphetamine-oral-fluid",
    "METHAMPHETAMINE ORAL FLUID": "methamphetamine-oral-fluid",
    "MDMA ORAL FLUID": "mdma-oral-fluid",
    "EXTENDED OPIATES ORAL FLUID": "extended-opiates-oral-fluid",
    "MORPHINE ORAL FLUID": "morphine-oral-fluid",
    "CODEINE ORAL FLUID": "codeine-oral-fluid",
    "HYDROCODONE ORAL FLUID": "hydrocodone-oral-fluid",
    "HYDROMORPHONE ORAL FLUID": "hydromorphone-oral-fluid",
    "OXYCODONE ORAL FLUID": "oxycodone-oral-fluid",
    "OXYMORPHONE ORAL FLUID": "oxymorphone-oral-fluid",
    "PHENCYCLIDINE ORAL FLUID": "phencyclidine-oral-fluid",
    "MARIJUANA ORAL FLUID": "marijuana-oral-fluid",
    "AMOBARBITAL ORAL FLUID": "amobarbital-oral-fluid",
    "BUTALBITAL ORAL FLUID": "butalbital-oral-fluid",
    "PHENOBARBITAL ORAL FLUID": "phenobarbital-oral-fluid",
    "PENTOBARBITAL ORAL FLUID": "pentobarbital-oral-fluid",
    "SECOBARBITAL ORAL FLUID": "secobarbital-oral-fluid",
    "BENZODIAZEPINES ORAL FLUID": "benzodiazepines-oral-fluid",
    "ALPRAZOLAM ORAL FLUID": "alprazolam-oral-fluid",
    "CLONAZEPAM ORAL FLUID": "clonazepam-oral-fluid",
    "LORAZEPAM ORAL FLUID": "lorazepam-oral-fluid",
    "OXAZEPAM ORAL FLUID": "oxazepam-oral-fluid",
    "TEMAZEPAM ORAL FLUID": "temazepam-oral-fluid",
    "NORDIAZEPAM ORAL FLUID": "nordiazepam-oral-fluid",
    "DIAZEPAM ORAL FLUID": "diazepam-oral-fluid",
    "EDDP ORAL FLUID": "eddp-oral-fluid",
    "METHADONE ORAL FLUID": "methadone-oral-fluid",
    "CREATININE": "creatinine",
    "PH": "ph",
    "DESIGNER STIMULANTS": "designer-stimulants",
    "4-METHYLMETHCATHINONE": "4-methylmethcathinone",
    "4-METHYLETHCATHINONE": "4-methylethcathinone",
    "BUPHEDRONE": "buphedrone",
    "BUTYLONE": "butylone",
    "BENZYLPIPERAZINE": "benzylpiperazine",
    "ETHYLONE": "ethylone",
    "EUTYLONE": "eutylone",
    "FLEPHEDRONE": "flephedrone",
    "MBDB": "mbdb",
    "MCPP": "mcpp",
    "MDAI": "mdai",
    "MDPBP": "mdpbp",
    "MDPV": "mdpv",
    "MEPHEDRONE": "mephedrone",
    "METHEDRONE": "methedrone",
    "METHYLONE": "methylone",
    "MITRAGYNINE (KRATOM)": "mitragynine",
    "NAPHYRONE": "naphyrone",
    "PENTEDRONE": "pentedrone",
    "PENTYLONE": "pentylone",
    "ALPHA-PVP": "alpha-pvp",
    "PYROVALERONE": "pyrovalerone",
    "CATHINONE": "cathinone",
    "METHCATHINONE": "methcathinone",
    "TFMPP": "tfmpp",
    "MDEAMETHYLENEDIOXYETHYLAMPHETAMINE" : "mdeamethylenedioxyethylamphetamine",
    "MDMAMETHYLENEDIOXYMETHAMPHETAMINE": "mdmamethylenedioxymethamphetamine",
}
    result_list = []
    for item in input_list_string.split(","):
        value = metabolist_list.get(item.strip(), "null")
        if value != "null":
            result_list.append(value)
    return  ", ".join(result_list)
